// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ramsey.NET.Models;

namespace Ramsey.NET.Migrations
{
    [DbContext(typeof(RamseyContext))]
    [Migration("20181205124855_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ramsey.NET.Models.Ingredient", b =>
                {
                    b.Property<string>("IngredientID");

                    b.Property<string>("RecipeMetaRecipeId");

                    b.HasKey("IngredientID");

                    b.HasIndex("RecipeMetaRecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Ramsey.NET.Models.RecipeMeta", b =>
                {
                    b.Property<string>("RecipeId");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int>("Owner");

                    b.Property<string>("OwnerLogo");

                    b.Property<string>("Source");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Ramsey.NET.Models.RecipePart", b =>
                {
                    b.Property<int>("RecipePartId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IngredientId");

                    b.Property<string>("RecipeId");

                    b.HasKey("RecipePartId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeParts");
                });

            modelBuilder.Entity("Ramsey.NET.Models.Ingredient", b =>
                {
                    b.HasOne("Ramsey.NET.Models.RecipeMeta")
                        .WithMany("RecipeParts")
                        .HasForeignKey("RecipeMetaRecipeId");
                });

            modelBuilder.Entity("Ramsey.NET.Models.RecipePart", b =>
                {
                    b.HasOne("Ramsey.NET.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeParts")
                        .HasForeignKey("IngredientId");

                    b.HasOne("Ramsey.NET.Models.RecipeMeta", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");
                });
#pragma warning restore 612, 618
        }
    }
}
