version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - calzone

  ramsey:
    image: ramsey.net:latest
    expose:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "@JagGillarJulmust"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express "
    expose:
      - "1433"