version: '3'

services:
  staging.api:
    build: .
    ports:
      - "5000:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Staging
  production.api:
    build: .
    ports:
      - "5001:80"
    environment:
- ASPNETCORE_ENVIRONMENT=Production