version: '3'

services:
  https-portal:
    image: steveltn/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - ramsey
    restart: always
    depends_on:
      - ramsey
    environment:
      DOMAINS: 'www.feedmeapp.se -> http://ramsey:80, api.feedmeapp.se -> http://ramsey:80'
      STAGE: 'production'

  ramsey:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  db:
    ports:
      - '5433:5432'
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ramsey
    expose:
      - "5432"